import sqlite3
db = sqlite3.connect("database.db")
c = db.cursor()
c.execute("CREATE TABLE IF NOT EXISTS authentication (id INTEGER PRIMARY KEY AUTOINCREMENT ,username TEXT UNIQUE,email TEXT,password TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS attempt (id INTEGER PRIMARY KEY AUTOINCREMENT ,device TEXT,username TEXT,attempt TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS another (device TEXT,username TEXT,date TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS attempttwo (id INTEGER PRIMARY KEY AUTOINCREMENT ,device TEXT,username TEXT,attempt TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS recovery (username TEXT,email TEXT,word TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS kickout (username TEXT,device TEXt)")
c.execute("CREATE TABLE IF NOT EXISTS setting (content TEXT,like TEXT,comment TEXT,chat TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS post (username TEXT,name TEXT,file BLOB,key TEXT,caption TEXT,id TEXT,date TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS like (username TEXT,postid TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS save (username TEXT,postid TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS follow (username TEXT,name TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS comment (postid TEXT,username TEXT,name TEXT,comment TEXT,messageid TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS chat (username TEXT,message TEXT,recipient TEXT)")
c.execute("CREATE TABLE IF NOT EXISTS profile (name TEXT,image TEXT)")
db.commit()
