import sqlite3
db = sqlite3.connect("database.db")
c = db.cursor()
c.execute("DELETE FROM another")
c.execute("DELETE FROM attempt")
c.execute("DELETE FROM attempttwo")
c.execute("DELETE FROM authentication")
c.execute("DELETE FROM chat")
c.execute("DELETE FROM comment")
c.execute("DELETE FROM follow")
c.execute("DELETE FROM kickout")
c.execute("DELETE FROM like")
c.execute("DELETE FROM post")
c.execute("DELETE FROM profile")
c.execute("DELETE FROM recovery")
c.execute("DELETE FROM save")
c.execute("DELETE FROM setting")
db.commit()